theme: jekyll-theme-leap-day

# For Atom Feed
domain: hanghliu.github.io
author: Hang Liu
email: hanghliu@gmail.com


# Site Settings
locale                   : "en-US"
# Keep original, do not replace
title                    : "Hello :)"
title_separator          : "-"
name                     : "Hang Liu"
description              : "HangLiu's GitHub pages."
